import os
import google.generativeai as genai
from dotenv import load_dotenv

# 1. Load environment variables from a .env file (if it exists)
load_dotenv()

# 2. Configure the Gemini API client using the key from our environment
# This will automatically look for the "GEMINI_API_KEY" variable
genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))

def generate_cover_letter(company_name, job_description_text):
    """
    Takes a company name and the scraped job description.
    Asks the Google Gemini LLM to write a professional 3-paragraph backend developer cover letter.
    """
    try:
        # 3. Specify the model we want to use
        # The API key you generated supports the newest 'gemini-2.5-flash' model
        model = genai.GenerativeModel('gemini-2.5-flash')
        
        # 4. Design the 'prompt' (the instructions we pass to the AI)
        prompt = f"""
        You are an expert Backend Python Developer applying for a job.
        Write a professional, exactly 3-paragraph cover letter for the following company and job description.
        
        Company Name: {company_name}
        
        Job Description:
        {job_description_text}
        
        Rules:
        1. Keep it professional and enthusiastic.
        2. Specifically mention my skills in Python, Flask, and building REST APIs.
        3. Do not include placeholder brackets like [Your Name] or [Address], leave them out naturally.
        4. Focus strongly on backend development and problem solving.
        5. It must be exactly 3 paragraphs: 
           - Paragraph 1: Introduction and excitement about the company.
           - Paragraph 2: Highlighting Python/Flask/Backend skills mapping to their requirements.
           - Paragraph 3: Conclusion and call to action.
        """
        
        # 5. Make the API call
        response = model.generate_content(prompt)
        
        # 6. Return the text generated by the AI
        return response.text
        
    except Exception as e:
        return f"Error generating cover letter: {str(e)}"

if __name__ == "__main__":
    # Test block
    print("Testing the AI Helper...")
    test_company = "Google"
    test_jd = "We are looking for a Python backend engineer with experience in Flask and REST APIs to join our cloud storage team."
    
    # We verify if the API key is present before trying
    if not os.environ.get("GEMINI_API_KEY"):
        print("ERROR: GEMINI_API_KEY is not set. Please create a .env file and add your key.")
    else:
        print(f"Generating letter for {test_company}...\n")
        letter = generate_cover_letter(test_company, test_jd)
        print("--- Generated Cover Letter ---\n")
        print(letter)
        print("\n------------------------------")
